### ISSUE TITLE
How to perform back testing?

### ISSUE THREAD

**Issue by tonypottera24** [lindomar-oliveira/backtrader-binance#11]
Sorry I'm new to backtrader.

Is there any way to use this package to test strategy on past data without placing real order?

**Comment by lindomar-oliveira** [comment]
@tonypottera24 I'm sorry for the late reply. Yes, it is possible.

Use [backtrader](https://github.com/mementum/backtrader) for that, without changing the default `Broker` and `Store`.

**Comment by simeneide** [comment]
Hi, i left a new issue before I saw this one. But if you remove broker&store, then you wouldnt use this package for anything? Not possible to download the data in "same format" using this?
