### ISSUE TITLE
Futures

### ISSUE THREAD

**Issue by piotrmajdanik** [lindomar-oliveira/backtrader-binance#12]
Hello, 
Have you maybe plan to add binance futures to backtrader_binance? :)
I'm strugged with add changes for it. But my skill of python is to low :(

I have done for now only: using futures data, running strategy in multiproceses and checking assets on futures account for each threaded pair coins.
But I need to also somehow creates bracket orders:
- BUY with market TP and SL (canceled all when one of them will be filled)
- SELL with market TP and SL (canceled all when one of them will be filled)
- receiving information about canceletion (for SELL or BUY brackets orders) - probably from user_stream_data (or sth. like this) to close also a position in backtrader strategy.

Can you somehow help me with understand how to do this? Or maybe you are working on this as a next version of backtrader_binance? :)

Thanks in advance for any feedback! ;)
BR, Piotr

**Comment by lindomar-oliveira** [comment]
#1 
@piotrmajdanik Thanks for using [backtrader-binance](https://github.com/lindomar-oliveira/backtrader-binance). I understand your interest in adding support for binance futures, but at the moment there is no forecast of your request, I will work on it at another time that is more favorable to me, like on my vacation.

**Comment by chan1919** [comment]
+1

**Comment by chan1919** [comment]
Now，i think ChatGPT helps
