### ISSUE TITLE
Update kline every second

### ISSUE THREAD

**Issue by zenoftrading** [lindomar-oliveira/backtrader-binance#3]
Hey. 

How can I get kline updates every second, like in the api implementation? https://binance-docs.github.io/apidocs/spot/en/#trade-streams

Or how can I get tick updates?

**Comment by lindomar-oliveira-martinello** [comment]
@zenoftrading  Sorry for the delay in replying.

The minimum candle/kline update time is 1 minute, it's link refers to the trade stream, that is, when there is buy and sell trading in your account.

**Comment by lindomar-oliveira** [comment]
@zenoftrading Sorry for the delay in replying.

The minimum candle/kline update time is 1 minute, it's link refers to the trade stream, that is, when there is buy and sell trading in your account.
