### ISSUE TITLE
Can't receive data when testnet=False

### ISSUE THREAD

**Issue by XZHhong** [lindomar-oliveira/backtrader-binance#5]
I change `testnet=False` to  `testnet=True` in the example which you give and run, and then I receive one data, but I can't receive any data after that. 
It seem that when `testnet=False` , websocket will be disconnected after a few seconds and will never be connected again. However I can receive data normally when `testnet=True`, and I can also use `class ThreadedWebsocketManager` normally  when `testnet=False` in other programs.

**Comment by lindomar-oliveira-martinello** [comment]
@XZHhong Still having problems with that?

**Comment by lindomar-oliveira** [comment]
@XZHhong Still having problems with that?
