### ISSUE TITLE
 Account has insufficient balance for requested action.

### ISSUE THREAD

**Issue by mmeftah** [lindomar-oliveira/backtrader-binance#6]
Hello,
thank you for your work. It appears that when I try the example code on Binance Spot (not the testnet) I have a BinanceApiException.  Account has insufficient balance for requested action.

I am looking at testing the algorithm with 100 EUR and targeting ETH/EUR.

What should be the minimum initial cash ? Can it be a parameter (like in fastquant).

Thanks

**Comment by lindomar-oliveira** [comment]
Hi @mmeftah,

1 - You must have EURO in your account.
PS.: When trading this symbol, for example you are buying ETH using your EUR balance. Check that the purchase amount (EUR) is not greater than your quote converted to EUR.
