### ISSUE TITLE
change the Strategy

### ISSUE THREAD

**Issue by xhl1993** [lindomar-oliveira/backtrader-binance#8]
class RSIStrategy(bt.Strategy):
    def __init__(self):
        self.rsi = bt.indicators.RSI(period=14)  # RSI indicator

    def next(self):

        print('Open: {}, High: {}, Low: {}, Close: {}'.format(
            self.data.open[0],
            self.data.high[0],
            self.data.low[0],
            self.data.close[0]))
        print('RSI: {}'.format(self.rsi[0]))

        if not self.position:
            if self.rsi < 30:  # Enter long
                self.buy()
        else:
            if self.rsi > 70:
                self.sell()  # Close long position

How to change it to an EMA policy or a Bolling policy in this instance，I change the bt.indicators.rsi as bt.indicators.ema  it casus problems.

**Comment by lindomar-oliveira** [comment]
@xhl1993 How is your code? How could I reproduce this?
