### ISSUE TITLE
How to use proxy?

### ISSUE THREAD

**Issue by chuzheng88** [lindomar-oliveira/backtrader-binance#9]
I have added proxies parameer code in binance_store.py, eg:
    def __init__(self, api_key, api_secret, coin_refer, coin_target, testnet=False, retries=5):
        proxies = {
            "http": "127.0.0.1:19180",
            "https": "127.0.0.1:19180"
        }
        # self.binance = Client(api_key, api_secret, testnet=testnet)
        self.binance = Client(api_key, api_secret, testnet=testnet, requests_params={"proxies": proxies})
        print(self.binance.get_account())
and I have print my account message, such as:
![image](https://user-images.githubusercontent.com/17675722/154832503-827807e1-5057-4254-b61b-2ec772057f81.png)

but my code also print error message, as follows:
![image](https://user-images.githubusercontent.com/17675722/154832538-cf06fc08-e57b-4bf6-9c8d-2fe66b3fa63a.png)

Can you help me?

**Comment by lindomar-oliveira** [comment]
@chuzheng88 Sounds right, is your proxy working properly?

See at: https://python-binance.readthedocs.io/en/latest/overview.html?highlight=proxy#requests-settings
